builders:
  model_builder:
    import: "package:crow_annotation_builder/builder.dart"
    builder_factories: ["convertBuilder"]
    build_extensions: {".dart": ["convert.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
