name: crow_annotation
description: Set of utils annotations which will save you the pain of writing boring code.
version: 0.0.2
homepage: https://github.com/elbeicktalat/crow/tree/master/packages/annotations/crow_annotation

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  meta: ^1.8.0

dev_dependencies:
  lints: ^2.0.0