name: crow
description: Crow gives you utils widgets, to apply separation of concerns.
version: 1.0.0
homepage: https://github.com/elbeicktalat/flutter_crow

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter